### ISSUE TITLE
Don't increase specificity

### ISSUE THREAD

**Issue by lttr** [postcss/postcss-dark-theme-class#22]
How do you work around the fact, that the added `html:not(.is-light)` increases selector specificity? Therefore such a ruleset wins even in situations where it would not according to the source CSS.

I suggest adding a `:where()` selector around it to lower the specificity.

**Comment by ai** [comment]
Great idea. We will release it as a major release with an option to disable `:where()`.

I added this feature to `main` 25f1189

Could you review the changes (check that I am using `:where()` right in the tests)?

**Comment by ai** [comment]
😥

OK, I released in 0.8.

**Comment by lttr** [comment]
Sorry for late response. I have just tried 0.8 on my codebase and it works very well. The usage of :where in tests seems good to me.

There is only one wierd behavior, which does not affect functionality and maybe a completely different topic. I have a nested `@supports` inside `@media` like this:

```css
@media (--OSdark) {
  :where(html) {
    @supports (color: color-mix(in srgb, white, black)) {
      --custom-property: ...;
    }
  }
}
```

which produces what seems like unnecessary amount of variants:

```css
@media (prefers-color-scheme: dark) {
  @supports (color: color-mix(in srgb, white, black)) {
    :where(html:where(:not(.is-light)):where(:not(.is-light)):where(:not(.is-light))) {
      --custom-property: ...;
    }
  }
}
@supports (color: color-mix(in srgb, white, black)) {
  :where(html:where(.is-dark):where(:not(.is-light)):where(:not(.is-light))) {
      --custom-property: ...;
  }
}
@supports (color: color-mix(in srgb, white, black)) {
  :where(html:where(.is-dark):where(:not(.is-light))) {
      --custom-property: ...;
  }
}
@supports (color: color-mix(in srgb, white, black)) {
  :where(html:where(.is-dark)) {
      --custom-property: ...;
  }
}
```

I can't wrap my head around it, so maybe it actually is necessary.

Thank you for your awesome work!
