### ISSUE TITLE
Add `light-dark()` support

### ISSUE THREAD

**Issue by ai** [postcss/postcss-dark-theme-class#25]
https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/light-dark

```css
a {
  color: light-dark(black, white);
}
```

```css
:where(html.is-dark) a {
  color: black;
}
:where(html.is-dark) a {
  color: white;
}
```
