### ISSUE TITLE
`!important` declaration is not being respected

### ISSUE THREAD

**Issue by yuheiy** [postcss/postcss-dark-theme-class#28]
When I include the `!important` declaration in a property value, it gets removed during the processing. Below is the CSS where this issue occurs:

```css
section {
  background: light-dark(white, black) !important;
}
```

will be processed to:

```css
@media (prefers-color-scheme:dark) {
    :where(html:not(.is-light)) section {
        background: black
    }
}
:where(html.is-dark) section {
    background: black
}
@media (prefers-color-scheme:light) {
    :where(html:not(.is-dark)) section {
        background: white
    }
}
:where(html.is-light) section {
    background: white
}
```

I believe the `!important` declaration should be preserved after transformation to ensure the intended styles remain prioritized.
