### ISSUE TITLE
Plugin breaks complex values when `light-dark` is nested

### ISSUE THREAD

**Issue by romainmenke** [postcss/postcss-dark-theme-class#30]
```css
.light-dark-function-mix-a {
	color: light-dark(color-mix(in oklch, red, light-dark(cyan, rgb(0, 0, 0))), blue);
}
```

becomes

```css
@media (prefers-color-scheme:dark) {

	:where(html:not(.is-light)) .light-dark-function-mix-a {
		color: blue;
	}
}

:where(html.is-dark) .light-dark-function-mix-a {
	color: blue;
}

@media (prefers-color-scheme:light) {

	:where(html:not(.is-dark)) .light-dark-function-mix-a {
		color: color-mix(in oklch, red, cyan;
	}
}

:where(html.is-light) .light-dark-function-mix-a {
	color: color-mix(in oklch, red, cyan;
}
```

`color: color-mix(in oklch, red, cyan;`

-----

Might be better to use a value parser for the value replacements :)

But as the title suggests, these are complex values that are unlikely to be used by authors.
