### ISSUE TITLE
Suggestion: allow to discard original syntax `@media (prefers-color-scheme: dark)`

### ISSUE THREAD

**Issue by aletorrado** [postcss/postcss-dark-theme-class#33]
Hi,

I just wanted to suggest adding a flag to the config to discard the original syntax, avoiding code duplication in the CSS output. This would help keeping the output code small when not needed.

For example, the app may add a little snippet like this on top: `document.documentElement.classList.toggle('is-dark', matchMedia('(prefers-color-scheme: dark)').matches)`

Please let me know if a PR would be welcomed.

Thanks!

**Comment by ai** [comment]
Hm. Can you show an input and output example for this option?

**Comment by aletorrado** [comment]
It would be the same output with the parts wrapped in the media queries stripped. Like this:

```less
/* Input CSS */

@media (prefers-color-scheme: dark) {
  html {
    --text-color: white
  }
  body {
    background: black
  }
}

section {
  background: light-dark(white, black);
}
```

```less
/* Output CSS */

html:where(.is-dark) {
  --text-color: white
}
:where(html.is-dark) body {
  background: black
}

:where(html.is-dark) section {
  background: black;
}
:where(html.is-light) section {
  background: white;
}
```
